---
kind: pipeline
type: docker
name: Tests

clone:
  depth: 50

steps:
- name: Tests
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  commands:
  - dotnet restore
  - dotnet build --configuration Release --no-restore
  - dotnet test --no-restore